import '@/app/globals.css'
import type { Metadata } from 'next'
import { Inter, Noto_Sans_KR } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const notoSansKr = Noto_Sans_KR({
    subsets: ["latin"],
    weight: ["500", "700"],
})

import StyledComponentsRegistry from './registry'
import ReduxProvider from "@/app/ReduxProvider";

import Test from "./test"


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cls(notoSansKr.className, inter.className)}>
        <ReduxProvider>
            <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </ReduxProvider>
      </body>
    </html>
  )
}

const cls = (...classnames: string[]) => {
    return classnames.join(" ");
};
